# Generated by Django 4.1.7 on 2023-12-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionvalue',
            old_name='value',
            new_name='ecg_value',
        ),
        migrations.AddField(
            model_name='predictionvalue',
            name='total_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
