# Generated by Django 4.1.7 on 2023-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_value_predictionvalue_ecg_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEcg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='ecg')),
            ],
        ),
    ]
